get temperature using entered coordinates
AllexUnderr/Weather pull request #1
Opened 2022-12-19 15:07 UTC by AllexUnderr

Now user can enter any coordinates

2022-12-21 10:19 UTC, MAX-POLKOVNIK requested changes
переделывай

2022-12-21 10:19 UTC, MAX-POLKOVNIK commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/MapView"
mapView с маленькой

2022-12-21 10:19 UTC, MAX-POLKOVNIK commented on app/src/main/res/values/styles.xml
> +    <style name="customEditText" parent="@android:style/Widget.EditText">
Стили называются с Большой буквы

2022-12-21 10:19 UTC, MAX-POLKOVNIK commented on app/src/main/java/com/example/weatherapplication/MainActivity.kt
> +    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
никто уже так не запрашивает разрешения

2022-12-21 10:19 UTC, MAX-POLKOVNIK commented on app/src/main/java/com/example/weatherapplication/MainActivity.kt
> +            if (latitude <= 90.0 && latitude >= -90.0 && longitude <= 180.0 && longitude >= -180) {
используй in оператор если надо проверить вхождение в range. latitude in -90..90

2022-12-21 10:19 UTC, MAX-POLKOVNIK commented on app/src/main/java/com/example/weatherapplication/MainActivity.kt
> +        getInstance().load(
что это делает?

2022-12-21 10:19 UTC, MAX-POLKOVNIK commented on app/src/main/java/com/example/weatherapplication/MainActivity.kt
>  import weatherAPI.Weather
эм, а почему API лежит вообще в другом package? он че в отдельном модуле?

2022-12-22 07:57 UTC, AllexUnderr commented on app/src/main/java/com/example/weatherapplication/MainActivity.kt
> +        getInstance().load(
это настройка для подгрузки карты. Что она делает - я не понимаю если честно. Но без этого, карта при увеличении не подгружается

2022-12-22 07:59 UTC, AllexUnderr commented on app/src/main/java/com/example/weatherapplication/MainActivity.kt
>  import weatherAPI.Weather
Да

2022-12-24 08:37 UTC, merged